### ISSUE TITLE
IndexError upon modifying the model for two head detection

### ISSUE THREAD

**Issue by eddyminer** [JiayuanWang-JW/YOLOv8-multi-task#13]
Sorry for troubling you again. I tried to remove one of the segmentation head as initial testing. However an error was encountered as below. I afraid any of my changes will affect the whole training process. Can you help up with this?

Starting training for 1 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss    Tv_loss    FL_loss  Instances       Size
  0%|          | 0/5834 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 12, in <module>
    model.train(data='/home/user/Desktop/two_head/ultralytics/datasets/bdd-multi.yaml', batch=12, epochs=1, imgsz=(640,640), name='yolopm', val=True, task='multi',classes=[2,3,4,9,10],combine_class=[2,3,4,9],single_cls=True)
  File "/home/user/.local/lib/python3.8/site-packages/ultralytics/yolo/engine/model.py", line 387, in train
    self.trainer.train()
  File "/home/user/.local/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 195, in train
    self._do_train(world_size)
  File "/home/user/.local/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 334, in _do_train
    for i, batch in pbar:
  File "/home/user/.local/lib/python3.8/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/home/user/.local/lib/python3.8/site-packages/ultralytics/yolo/data/build.py", line 38, in __iter__
    yield next(self.iterator)
  File "/home/user/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/user/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/home/user/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/home/user/.local/lib/python3.8/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/user/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/user/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/user/.local/lib/python3.8/site-packages/ultralytics/yolo/data/base.py", line 282, in __getitem__
    transfer = self.transforms(label_list)
  File "/home/user/.local/lib/python3.8/site-packages/ultralytics/yolo/data/augment.py", line 56, in __call__
    data = t(data)
  File "/home/user/.local/lib/python3.8/site-packages/ultralytics/yolo/data/augment.py", line 56, in __call__
    data = t(data)
  File "/home/user/.local/lib/python3.8/site-packages/ultralytics/yolo/data/augment.py", line 108, in __call__
    tem_list = [file[count] for file in mix_labels]
  File "/home/user/.local/lib/python3.8/site-packages/ultralytics/yolo/data/augment.py", line 108, in <listcomp>
    tem_list = [file[count] for file in mix_labels]
IndexError: list index out of range

**Comment by liu-haoyu** [comment]
I have encountered the same problem. May I ask if you have resolved this issue? I hope to receive some guidance from you. Thank you very much

**Comment by 2395268040** [comment]
I'm also running into this issue, please how can I fix it

**Comment by LiuJinchao000** [comment]
I'm also running into this issue, please how can I fix it

**Comment by kokun66** [comment]
Anybody made it?

**Comment by kokun66** [comment]
Seems I failed at validation after one epoch:
Traceback (most recent call last):
  File "/project/davinci_users/software/qun.gu/workspace/arch-mt_det/./multi-task/ultralytics/mt_train.py", line 79, in <module>
    main(args)
  File "/project/davinci_users/software/qun.gu/workspace/arch-mt_det/./multi-task/ultralytics/mt_train.py", line 46, in main
    model.train(data=dataset_cfg, 
  File "/project/davinci_users/software/qun.gu/workspace/arch-mt_det/multi-task/ultralytics/yolo/engine/model.py", line 387, in train
    self.trainer.train()
  File "/project/davinci_users/software/qun.gu/workspace/arch-mt_det/multi-task/ultralytics/yolo/engine/trainer.py", line 195, in train
    self._do_train(world_size)
  File "/project/davinci_users/software/qun.gu/workspace/arch-mt_det/multi-task/ultralytics/yolo/engine/trainer.py", line 445, in _do_train
    self.metrics, self.fitness = self.validate()
  File "/project/davinci_users/software/qun.gu/workspace/arch-mt_det/multi-task/ultralytics/yolo/engine/trainer.py", line 562, in validate
    metrics_list = self.validator(self)
  File "/home/qun.gu/miniconda3/envs/mt_det_conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/project/davinci_users/software/qun.gu/workspace/arch-mt_det/multi-task/ultralytics/yolo/engine/validator.py", line 266, in __call__
    self.update_metrics_det(preds_list_post[i], batch[i], label_name)
  File "/project/davinci_users/software/qun.gu/workspace/arch-mt_det/multi-task/ultralytics/yolo/v8/DecSeg/val.py", line 138, in update_metrics_det
    cls = self.replace_elements_in_column(cls,self.args.combine_class,0)
  File "/project/davinci_users/software/qun.gu/workspace/arch-mt_det/multi-task/ultralytics/yolo/v8/DecSeg/val.py", line 124, in replace_elements_in_column
    target_list = torch.tensor(target_list, dtype=torch.float32, device=self.device)
TypeError: new(): invalid data type 'str'

**Comment by zhaozijun0225** [comment]
Just check the dateset whether having 'corrupt'.
