### ISSUE TITLE
这个问题怎么回事

### ISSUE THREAD

**Issue by worlkingbling** [JiayuanWang-JW/YOLOv8-multi-task#49]
Traceback (most recent call last):
  File "D:/Pycharm/YOLOv8-multi-task-main/ultralytics/predict.py", line 9, in <module>
    model.predict(source='data/1.mp4', imgsz=(384,672), device='cpu',name='v4', stream=True,save=True,conf=0.25, iou=0.45, show_labels=False)
  File "D:\ANACONDA\envs\yolov8\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Pycharm\YOLOv8-multi-task-main\ultralytics\yolo\engine\model.py", line 269, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "D:\Pycharm\YOLOv8-multi-task-main\ultralytics\yolo\engine\predictor_multi.py", line 194, in __call__
    return self.stream_inference(source, model)
  File "D:\ANACONDA\envs\yolov8\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Pycharm\YOLOv8-multi-task-main\ultralytics\yolo\engine\predictor_multi.py", line 289, in stream_inference
    self.save_preds(vid_cap, i, str(self.save_dir / p.name))
  File "D:\Pycharm\YOLOv8-multi-task-main\ultralytics\yolo\engine\predictor_multi.py", line 384, in save_preds
    self.vid_writer[idx].write(im0)
UnboundLocalError: local variable 'im0' referenced before assignment

进程已结束,退出代码1

**Comment by JiayuanWang-JW** [comment]
因为您的输入是一段视频而不是图像，本库只针对图像进行了多任务处理，目前还没有扩展到视频。
