### ISSUE TITLE
train.cache 

### ISSUE THREAD

**Issue by worlkingbling** [JiayuanWang-JW/YOLOv8-multi-task#52]
Traceback (most recent call last):
  File "D:/Pycharm/YOLOv8-multi-task-main/ultralytics/train.py", line 12, in <module>
    model.train(data='D:/Pycharm/YOLOv8-multi-task-main/ultralytics/datasets/bdd-multi.yaml', batch=4, epochs=30, imgsz=(640,640), device='cpu', name='yolom', val=True, task='multi',classes=[2,3,4,9,10,11],combine_class=[2,3,4,9],single_cls=True)
  File "D:\Pycharm\YOLOv8-multi-task-main\ultralytics\yolo\engine\model.py", line 387, in train
    self.trainer.train()
  File "D:\Pycharm\YOLOv8-multi-task-main\ultralytics\yolo\engine\trainer.py", line 195, in train
    self._do_train(world_size)
  File "D:\Pycharm\YOLOv8-multi-task-main\ultralytics\yolo\engine\trainer.py", line 292, in _do_train
    self._setup_train(world_size)
  File "D:\Pycharm\YOLOv8-multi-task-main\ultralytics\yolo\engine\trainer.py", line 263, in _setup_train
    self.train_loader = self.get_dataloader(self.trainset, batch_size=batch_size, rank=RANK, mode='train')
  File "D:\Pycharm\YOLOv8-multi-task-main\ultralytics\yolo\v8\DecSeg\train.py", line 71, in get_dataloader
    dataset = self.build_dataset(dataset_path, mode, batch_size)
  File "D:\Pycharm\YOLOv8-multi-task-main\ultralytics\yolo\v8\DecSeg\train.py", line 45, in build_dataset
    return build_yolo_dataset(self.args, img_path, batch, self.data, mode=mode, rect=mode == 'val', stride=gs)
  File "D:\Pycharm\YOLOv8-multi-task-main\ultralytics\yolo\data\build.py", line 74, in build_yolo_dataset
    return YOLODataset(
  File "D:\Pycharm\YOLOv8-multi-task-main\ultralytics\yolo\data\dataset.py", line 40, in __init__
    super().__init__(*args, **kwargs)
  File "D:\Pycharm\YOLOv8-multi-task-main\ultralytics\yolo\data\base.py", line 70, in __init__
    self.labels = self.get_multi_labels()
  File "D:\Pycharm\YOLOv8-multi-task-main\ultralytics\yolo\data\dataset.py", line 170, in get_multi_labels
    raise FileNotFoundError(f'{self.prefix}No labels found in {cache_path}, can not start training. {HELP_URL}')
FileNotFoundError: train: No labels found in F:\BaiduNetdiskDownload\bdd100k\detection-object\labels\100k\train.cache, can not start training. See https://docs.ultralytics.com/yolov5/tutorials/train_custom_data

**Comment by Venkat-1405** [comment]
same issue here

**Comment by AZong76** [comment]
May I ask if you have resolved it？

**Comment by AZong76** [comment]
> same issue here

May I ask if you have resolved it？

**Comment by Venkat-1405** [comment]
> > same issue here
> 
> May I ask if you have resolved it？

It is resolved by removing the old cache generated in the dataset path and once again update the path in the yaml and start training

**Comment by MartinPR307** [comment]
@Venkat-1405 Hello, even after following your instructions, the same issue still occurs. Additionally, what does the phrase "once again update the path in the yaml" mean?

**Comment by haheheixi** [comment]
My original validation images path was images/val, and the test images path was also images/val. I encountered this problem, but later I changed the paths to images/val2017 and images/val2017, which solved the issue.
