### ISSUE TITLE
请问一下 这个错误是怎么回事啊？

### ISSUE THREAD

**Issue by worlkingbling** [JiayuanWang-JW/YOLOv8-multi-task#53]
Traceback (most recent call last):
  File "ultralytics/train.py", line 7, in <module>
    model = YOLO('./ultralytics/models/v8/yolov8-bdd-v4-one-dropout-individual-n.yaml', task='multi')  # build a new model from YAML
  File "/root/miniconda3/envs/myconda/lib/python3.8/site-packages/ultralytics/models/yolo/model.py", line 23, in __init__
    super().__init__(model=model, task=task, verbose=verbose)
  File "/root/miniconda3/envs/myconda/lib/python3.8/site-packages/ultralytics/engine/model.py", line 150, in __init__
    self._new(model, task=task, verbose=verbose)
  File "/root/miniconda3/envs/myconda/lib/python3.8/site-packages/ultralytics/engine/model.py", line 219, in _new
    self.model = (model or self._smart_load("model"))(cfg_dict, verbose=verbose and RANK == -1)  # build model
  File "/root/miniconda3/envs/myconda/lib/python3.8/site-packages/ultralytics/engine/model.py", line 834, in _smart_load
    raise NotImplementedError(
NotImplementedError: WARNING ⚠️ 'YOLO' model does not support '_new' mode for 'multi' task yet.

**Comment by QiTianDaShengDaShi** [comment]
你这个找到python 环境的yolo 去了，你用pycharm运行，或者先在终端指定一下python工作目录

**Comment by JiayuanWang-JW** [comment]
Hi @QiTianDaShengDaShi， 谢谢您为该库做的贡献，您的回答非常正确。
Hi @worlkingbling， 请严格按照我的readme说明去安装环境，您不能直接使用YOLOv8官方提供的命令直接安装`pip install ultralytics`。否则您的环境一直使用的是最底层的ultralytics文件，您在[YOLOv8-multi-task](https://github.com/JiayuanWang-JW/YOLOv8-multi-task)目录下的任何修改都不会起作用。

如果有任何疑问，请重新打开issue，谢谢。
