### ISSUE TITLE
求助 这个是怎么回事 所以数据集的目录都是对的 还显示这个错误

### ISSUE THREAD

**Issue by worlkingbling** [JiayuanWang-JW/YOLOv8-multi-task#54]
Traceback (most recent call last):
  File "ultralytics/train.py", line 12, in <module>
    model.train(data='./ultralytics/datasets/bdd-multi.yaml', batch=16, epochs=100, imgsz=(640,640), device=0, name='yoloml', val=True, task='multi',classes=[2,3,4,9,10,11],combine_class=[2,3,4,9],single_cls=True)
  File "/root/miniconda3/envs/myconda/lib/python3.8/site-packages/ultralytics/yolo/engine/model.py", line 382, in train
    self.trainer = TASK_MAP[self.task][1](overrides=overrides, _callbacks=self.callbacks)
  File "/root/miniconda3/envs/myconda/lib/python3.8/site-packages/ultralytics/yolo/v8/DecSeg/train.py", line 31, in __init__
    super().__init__(cfg, overrides, _callbacks)
  File "/root/miniconda3/envs/myconda/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 127, in __init__
    raise RuntimeError(emojis(f"Dataset '{clean_url(self.args.data)}' error ❌ {e}")) from e
RuntimeError: Dataset 'ultralytics/datasets/bdd-multi.yaml' error ❌ 
Dataset 'ultralytics/datasets/bdd-multi.yaml' images not found ⚠️, missing paths ['/ultralytics/bdd100k/images/val2017']
Note dataset download directory is '/mnt/YOLOv8-multi-task-main/datasets'. You can update this in '/root/.config/Ultralytics/settings.yaml'

**Comment by JiayuanWang-JW** [comment]
Hi @worlkingbling， 请参阅[issue53](https://github.com/JiayuanWang-JW/YOLOv8-multi-task/issues/53#issuecomment-2121370806)去重新安装环境就可以了，您现在的环境使用的是最底层的ultralytics，您在YOLOv8-multi-task-main文件下的任何修改都不会起作用，这也是为什么我在readme中强烈要求大家使用我提供的方法安装ultralytics库。

如按照上述方法操作后还有问题，请重新打开这个issue，谢谢。
