### ISSUE TITLE
 AttributeError: 'list' object has no attribute 'sum'

### ISSUE THREAD

**Issue by jasfa** [JiayuanWang-JW/YOLOv8-multi-task#75]
Why did this error occur after 60 epochs of training and entering the verification phase？

Traceback (most recent call last):
  File "train.py", line 12, in <module>
    model.train(data='ultralytics/datasets/bdd-multi.yaml', batch=4, epochs=60, imgsz=(640,640), device=[0], name='exp', workers=24, val=True, task='multi',classes=[2,3,4,9,10,11],combine_class=[2,3,4,9],single_cls=True)
  File "ultralytics/yolo/engine/model.py", line 387, in train
    self.trainer.train()
  File "ultralytics/yolo/engine/trainer.py", line 195, in train
    self._do_train(world_size)
  File "ultralytics/yolo/engine/trainer.py", line 447, in _do_train
    self.metrics, self.fitness = self.validate()
  File "ultralytics/yolo/engine/trainer.py", line 564, in validate
    metrics_list = self.validator(self)
  File "/root/env/env/yolov8-multi/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "ultralytics/yolo/engine/validator.py", line 288, in __call__
    self.print_results()
  File "ultralytics/yolo/v8/DecSeg/val.py", line 349, in print_results
    LOGGER.info(pf % ('all', self.seen[label_name], self.nt_per_class[label_name].sum(), *self.metrics[count].mean_results()))
AttributeError: 'list' object has no attribute 'sum'

**Comment by JiayuanWang-JW** [comment]
Did you change any parts? In repositories code, print_results function in line [270](https://github.com/JiayuanWang-JW/YOLOv8-multi-task/blob/32824bb90542bcd6d24831eec7c9c911b40c181f/ultralytics/yolo/v8/DecSeg/val.py#L270), not in 349.

**Comment by jasfa** [comment]
> Did you change any parts? In repositories code, print_results function in line [270](https://github.com/JiayuanWang-JW/YOLOv8-multi-task/blob/32824bb90542bcd6d24831eec7c9c911b40c181f/ultralytics/yolo/v8/DecSeg/val.py#L270), not in 349.

I'm sorry, it's my problem
